server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  # Routing Configuration
  cloud:
    gateway:
      routes:
        - id: ADMIN-SERVICE
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**

        - id: REMITTER-SERVICE
          uri: lb://REMITTER-SERVICE
          predicates:
            - Path=/remitter/**

        - id: BENEFICIARY-SERVICE
          uri: lb://BENEFICIARY-SERVICE
          predicates:
            - Path=/beneficiary/**

# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost